### ISSUE TITLE
Upon saving a model config in Moodle LA without making changes, a new config is created in LaLA

### ISSUE THREAD

**Issue by LiFaytheGoblin** [LiFaytheGoblin/moodle-tool_lala#26]
On branch 14-ui-improvements

**Steps to reproduce:**
- create a new model in Moodle LA
- go to the plugin page: a new config has been created
- in the Moodle LA, click on edit model and save it without making any changes
- go to the plugin page: a new config has been created 

**Unexpected behavior:**
Yet another config has been created, with identical properties as the first one.

**Screenshot:** 
![image](https://github.com/LiFaytheGoblin/moodle-tool_lala/assets/5471273/ac6780a7-affa-4cf3-9d2c-eb1cef0a4421)

**Expected Behavior:**
No new config should be created, if an identical config exists already.

**Todo:**
- [ ] fix the issue
- [ ] make sure there is a working automatic test to catch this case

**Comment by ciprianpopa** [comment]
Looking into this issue.

**Comment by ciprianpopa** [comment]
Hey Linda
I cannot push the commit, but this is how I would replace those two checks for the New or Changed models, because it gives you more flexibility and you could add more conditions using the column names if needed.

`        $neworchangedmodels = $DB->get_records_sql('SELECT * FROM {analytics_models} am 
            WHERE NOT EXISTS (
                SELECT 1 FROM {tool_lala_model_configs} tlmc 
                WHERE
                (am.predictionsprocessor = tlmc.predictionsprocessor OR ((am.predictionsprocessor IS NOT NULL OR am.predictionsprocessor <> "") AND am.predictionsprocessor <> tlmc.predictionsprocessor))
                 AND (am.timesplitting = tlmc.analysisinterval  OR ((am.timesplitting IS NOT NULL OR am.timesplitting <> "") AND am.timesplitting <> tlmc.analysisinterval))
                 AND am.indicators = tlmc.indicators
                 AND am.id = tlmc.modelid
                )
        ');

        foreach ($neworchangedmodels as $neworchangedmodel){
            self::create_and_get_for_model($changedmodel->id);
        }`

**Comment by LiFaytheGoblin** [comment]
> Hey Linda I cannot push the commit, but this is how I would replace those two checks for the New or Changed models, because it gives you more flexibility and you could add more conditions using the column names if needed.
> 
> ```
>  $neworchangedmodels = $DB->get_records_sql('SELECT * FROM {analytics_models} am 
>             WHERE NOT EXISTS (
>                 SELECT 1 FROM {tool_lala_model_configs} tlmc 
>                 WHERE
>                 (am.predictionsprocessor = tlmc.predictionsprocessor OR ((am.predictionsprocessor IS NOT NULL OR am.predictionsprocessor <> "") AND am.predictionsprocessor <> tlmc.predictionsprocessor))
>                  AND (am.timesplitting = tlmc.analysisinterval  OR ((am.timesplitting IS NOT NULL OR am.timesplitting <> "") AND am.timesplitting <> tlmc.analysisinterval))
>                  AND am.indicators = tlmc.indicators
>                  AND am.id = tlmc.modelid
>                 )
>         ');
> 
>         foreach ($neworchangedmodels as $neworchangedmodel){
>             self::create_and_get_for_model($changedmodel->id);
>         }
> ```

Thanks so much @ciprianpopa, I will try it out and tell you how it goes! 

(On a side note: I limited pushing to team members only, but others can fork this project and make a push request for their fork.)

**Comment by LiFaytheGoblin** [comment]
It's really weird. No matter what I try, it does not work. ChatGPT doesn't know anything else either. I might return to doing it with PHP.

**Comment by LiFaytheGoblin** [comment]
I can't get it right, I am going back to doing it via php and dml^^
