### ISSUE TITLE
Deprecated json_decode() call

### ISSUE THREAD

**Issue by mudrd8mz** [LiFaytheGoblin/moodle-tool_lala#48]
On the plugin's main page, I am getting the following debugging message:

```
Deprecated: json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in admin/tool/lala/classes/output/model_configuration.php on line 75
```

**Comment by LiFaytheGoblin** [comment]
Hi @mudrd8mz! Thanks for starting the review of my plugin. Which version are you checking? Since submitting the plugin I have published 2 more version and we are now at v4.

**Comment by mudrd8mz** [comment]
Hi. We always check the versions from https://moodle.org/plugins/tool_lala/versions - i.e. those published in the Plugins directory. If you have more recent versions in your Git repository, they should be released in the plugins directory, too.

**Comment by LiFaytheGoblin** [comment]
This was fixed in newer versions
